### ISSUE TITLE
[2.2a] Crash on Startup Involving Dummy Module Mods

### ISSUE THREAD

**Issue by PitchBright** [Mitchellbrine/DiseaseCraft-2.0#10]
DiseaseCraft-1.7.10-2.2a-dev
http://pastebin.com/PdGWCjYX

**Comment by Mitchellbrine** [comment]
This is because there are no modules in the ClassHelper. The only way this
can happen is if it doesn't load.

Try adding
- Dfml.coreMods.load=mc.Mitchellbrine.diseaseCraft.coremod.DCCoreMod

in your VM arguments and see if the problem persists.

**Comment by PitchBright** [comment]
I'll close this up after I test the right file. My bad.

**Comment by PitchBright** [comment]
Different crash, this time with the correct jar file.

DiseaseCraft-1.7.10-2.2a
http://pastebin.com/xQumY1GL

**Comment by Mitchellbrine** [comment]
Is there anything more to the crash log? The error doesn't reference my code (at least so far in the stacktrace). Could you provide the full crash report?

**Comment by PitchBright** [comment]
That's all there is really. I left out the system details. I fired it up again, just to make sure it happens every time.  http://pastebin.com/YzP55K5r

It doesn't happen when I remove the mod. So that's what made me think it was related to DiseaseCraft.

**Comment by Mitchellbrine** [comment]
I need to see the part with the letters next to the mod names (it would tell me for sure if DiseaseCraft caused it (as it could be an incompatibility with another mod and DC and if so, I need to know which)

**Comment by PitchBright** [comment]
Oh, I didn't realize that, sorry. Does that last report show you what you need?

**Comment by Mitchellbrine** [comment]
It cuts off before. So close XD

**Comment by PitchBright** [comment]
That's the whole report. Sending you the last two reports via IM. Not sure what else I can give you to show you where the problem lies. Ideas?

**Comment by Mitchellbrine** [comment]
Alright, taking a look at the top of the stacktrace, I believe the problem lies in the dummy mods given to modules. Confirming.
