### ISSUE TITLE
[2.2.0.1a] Crash on world load

### ISSUE THREAD

**Issue by amdorj** [Mitchellbrine/DiseaseCraft-2.0#12]
The crash happens whenever I load a world. I posted a crash report on Gist so you can (hopefully) fix it. I used the DiseaseCraft.json file I found here on GitHub (diseaseJSON/DiseaseCraft.json). I am using the Latest forge 1.7.10 build [forge-1.7.10-10.13.4.1614-1.7.10] and using 2.2.0.1a of DC.

https://gist.github.com/amdorj/3478b994f78905308061

**Comment by Mitchellbrine** [comment]
That's because the json file in diseaseJSON is out of date with current
builds. The up-to-date one is under the
src/main/resources/assets/DiseaseCraft/diseases/ folder.

I'll be sure to update the version in the diseaseJSON/ folder with a commit
closing this in a bit

**Comment by amdorj** [comment]
New crash:
https://gist.github.com/amdorj/04776cc82c3dead0cd7f

I downloaded the file in the src/.../diseases
