### ISSUE TITLE
None of the diseases work

### ISSUE THREAD

**Issue by lukefox01** [Mitchellbrine/DiseaseCraft-2.0#17]
I dont know what im doing wrong but the vials of diseases and medications appear in the creative menu and the mod seems to work but when i inject myself with diseases nothing happens. I played diseasecraft 1 a year ago and it worked flawlessly now this version doesnt really work at all. I already tried re-installing and im using version 2.3

**Comment by lukefox01** [comment]
I dont get the problem I've since tried the mod with 2 other versions of forge and I've also tried version 2.1 and 2.0 of the mod and none of them work. But this is the wierd part it doesnt crash and everything looks fine at first. The objects are in the creative menu, you can use the syringes, and i can even eat and overdose and medications but when it comes to the actually diseases it doesnt work. I have tried any way to fix it I know and to no avail. Wolf bites wont give me rabies even when they bite me over 100 times, rats dont get me sick, and just plain injections of the disease dont work. I really want to play this mod as i played it in 1.0 with no problem around a year ago and now you improved it so much and i cant get the actually diseases to work. This is so strange and I have no idea what is causing the problem. Any ideas? Also i have another question with custom diseases in the json file do you have to specify player to player transmission or is that already in other code. And when it comes to this code 
      "type":"mob",
      "parameters":[
        3,
        999000,
        "DiseaseCraft.rat"
I am confused. When you want to spread by mod what are the parameters. I see the number 3 and 999000 and I have no idea what that means.

EDIT
I just tried diseasecraft v2.1 and this time i put the disease json file in the mod folder as I figured out it wasnt in the jar and now it works perfectly, however, I still am not able to get version 2.3 to work.

**Comment by Mitchellbrine** [comment]
Fixed in the quickfix
